# Generates a random unlock password, prints it ONCE to the console, and writes
# its SHA-256 hash into app/src/main/java/com/nico/minidpc/PasswordHash.kt.
#
# Workflow:
#   1. Run this script.
#   2. Copy the printed password and send it to your girlfriend (or wherever).
#   3. Close this terminal — the password is not stored anywhere on disk.
#   4. Rebuild the APK and install. The hash is baked in.
#
# After running, you (the user) will not remember the password. Only the hash
# remains in the source code. The plaintext is only in this terminal window
# until you close it.

param(
    [int]$Length = 24
)

# Generate random URL-safe password
$bytes = New-Object byte[] $Length
[System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
$password = [Convert]::ToBase64String($bytes).TrimEnd('=').Replace('+','-').Replace('/','_').Substring(0, $Length)

# Compute SHA-256 hex
$sha = [System.Security.Cryptography.SHA256]::Create()
$hashBytes = $sha.ComputeHash([System.Text.Encoding]::UTF8.GetBytes($password))
$hashHex = -join ($hashBytes | ForEach-Object { $_.ToString('x2') })

# Update PasswordHash.kt
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition
$kotlinFile = Join-Path $scriptDir "app\src\main\java\com\nico\minidpc\PasswordHash.kt"
$content = @"
package com.nico.minidpc

// SHA-256 hash of the unlock password.
// Generated by set-password.ps1 — do not edit by hand.
object PasswordHash {
    const val SHA256 = "$hashHex"
}
"@
Set-Content -Path $kotlinFile -Value $content -Encoding UTF8

Write-Host ""
Write-Host "=========================================="
Write-Host "PASSWORD (copy NOW, will not be shown again):"
Write-Host ""
Write-Host "    $password"
Write-Host ""
Write-Host "Hash written to:"
Write-Host "    $kotlinFile"
Write-Host "=========================================="
Write-Host ""
Write-Host "Next: build the APK (Android Studio or 'gradlew assembleDebug')"
