package com.nico.minidpc

// SHA-256 hash of the unlock password.
// Generated by set-password.ps1 â€” do not edit by hand.
object PasswordHash {
    const val SHA256 = "51623714d2a06cc9394cac97cc0f5bb73dcbb9d33449248476d4eef5730a03aa"
}
